services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=adesampa
      - DB_USER=hugo
      - DB_PASSWORD=adesampa
      
  db:
    build:
      context: ./db
    restart: always
    environment:
      - POSTGRES_DB=adesampa
      - POSTGRES_USER=hugo
      - POSTGRES_PASSWORD=adesampa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

